### ISSUE TITLE
CSS Framework or No CSS Framework?

### ISSUE THREAD

**Issue by Rushmead** [CraftTogether/CraftWeb#5]
Oooh, do we want to use a CSS Framework or not?

If so:
- Material?
- Bootstrap
- Foundation
- Other?

I will make two comments, please +1 on the one you want. Once that's pretty much done i'll add another for the different frameworks.

**Comment by Rushmead** [comment]
CSS Framework (Upvote for Vote)

**Comment by Rushmead** [comment]
No CSS Framework (+1 for vote)

**Comment by njb-said** [comment]
I think we should do something, but not rely on it too much.
Something lightweight would be good probably

(For other frameworks, we should definitely use jQuery to make life easier)

**Comment by Rushmead** [comment]
Alrighty, looks like a general Yes for a CSS framework. Next up: What framework? Please vote on the following comments!

**Comment by Rushmead** [comment]
Bootstrap (+1 for vote)

**Comment by Rushmead** [comment]
Materialize (+1 for vote)

**Comment by Rushmead** [comment]
Foundation (+1 for vote)

**Comment by Rushmead** [comment]
Other (+1 for vote)

**Comment by iamjawa** [comment]
Maybe use Foundation's Grid system (Since more people have knowledge on how to implement it properly) while taking the components from Materialize?
